export const ROUND_MARKET_ABI = [
  { type: 'function', name: 'pair', inputs: [], outputs: [{ type: 'string' }], stateMutability: 'view' },
  { type: 'function', name: 'totalBetsCount', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'minBetAmount', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'protocolFeeBps', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'activeUpPool', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'activeDownPool', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'virtualUp', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'virtualDown', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  { type: 'function', name: 'latestPrice', inputs: [], outputs: [{ type: 'int256' }], stateMutability: 'view' },
  { type: 'function', name: 'latestPriceTimestamp', inputs: [], outputs: [{ type: 'uint256' }], stateMutability: 'view' },
  {
    type: 'function',
    name: 'getBet',
    inputs: [{ name: 'betId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'betId', type: 'uint256' },
          { name: 'user', type: 'address' },
          { name: 'position', type: 'uint8' },
          { name: 'stake', type: 'uint256' },
          { name: 'entryTime', type: 'uint256' },
          { name: 'expiryTime', type: 'uint256' },
          { name: 'entryPrice', type: 'int256' },
          { name: 'settlementPrice', type: 'int256' },
          { name: 'lockedMultiplier', type: 'uint256' },
          { name: 'status', type: 'uint8' },
          { name: 'payout', type: 'uint256' },
          { name: 'claimed', type: 'bool' },
        ],
      },
    ],
    stateMutability: 'view',
  },
  { type: 'function', name: 'getUserBets', inputs: [{ name: 'user', type: 'address' }], outputs: [{ type: 'uint256[]' }], stateMutability: 'view' },
  {
    type: 'function',
    name: 'getLiveMultipliers',
    inputs: [],
    outputs: [
      { name: 'upMultiplier', type: 'uint256' },
      { name: 'downMultiplier', type: 'uint256' },
    ],
    stateMutability: 'view',
  },
  { type: 'function', name: 'placeBet', inputs: [{ name: 'position', type: 'uint8' }], outputs: [], stateMutability: 'payable' },
  { type: 'function', name: 'pushPrice', inputs: [{ name: 'price', type: 'int256' }], outputs: [], stateMutability: 'nonpayable' },
  { type: 'function', name: 'resolveBet', inputs: [{ name: 'betId', type: 'uint256' }, { name: 'settlementPrice', type: 'int256' }], outputs: [], stateMutability: 'nonpayable' },
] as const;
